---
# resources:
#   - name: concourse-tests
#     type: git
#     source:
#       uri: git@github.com:utricularian/concourse-tests.git
#       branch: master

jobs:
- name: on-commit-bump-timestamp
  plan:
    - task: echo-timestamps
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: { repository: ubuntu }
        run:
          path: sh
          args:
            - -exc
            - |
              whoami
              env
              go version
              find .
              touch ephemeral-thing

#     - get: concourse-tests
#       version: latest
#       trigger: true
#     - task: add-timestamp-to-concourse-tests
#       file: concourse-tests/tasks/add-timestamp-to-concourse-tests.yml
#     - put: concourse-tests

