---
resources:
  - name: concourse-tests
    type: git
    source:
      uri: git@github.com:utricularian/concourse-tests.git
      branch: master
      private_key: ((resource-git-read-only))
  - name: concourse-tests-writeable
    type: git
    source:
      uri: git@github.com:utricularian/concourse-tests.git
      branch: master
      private_key: ((resource-git-read-write))

jobs:
- name: on-commit-bump-timestamp
  plan:
    - get: concourse-tests
      version: latest
      trigger: true
    - task: add-timestamp-to-concourse-tests
      file: concourse-tests/tasks/add-timestamp-to-concourse-tests.yml
    - task: do-other-stuff-to-concourse-tests
      file: concourse-tests/tasks/do-other-stuff-to-concourse-tests.yml
    - put: concourse-tests-writeable
      params:
        repository: concourse-tests-dirty

