---
resources:
  - name: concourse-tests
    type: git
    source:
      uri: git@github.com:utricularian/concourse-tests.git
      branch: develop
      private_key: ((resource-git-read-write))

  - name: concourse-tests-release-candidate
    type: git
    source:
      uri: git@github.com:utricularian/concourse-tests.git
      branch: release-candidate
      private_key: ((resource-git-read-write))

  - name: concourse-tests-master
    type: git
    source:
      uri: git@github.com:utricularian/concourse-tests.git
      branch: master
      private_key: ((resource-git-read-write))

  - name: concourse-tests-version
    type: semver
    source:
      driver: git
      uri: git@github.com:utricularian/concourse-semvers.git
      branch: master
      file: concourse-tests.version
      private_key: ((resource-semver-read-write))

jobs:
- name: pretend-to-do-stuff
  plan:
    - get: concourse-tests
      trigger: true
    - task: sleep-for-a-bit
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: concourse/bosh-cli}
        run:
          path: sleep
          args: [10]

- name: promote-to-rc
  plan:
    - get: concourse-tests-version
      params:
        pre: rc
    - get: concourse-tests
      passed: [pretend-to-do-stuff]
      trigger: true
      params:
        fetch: [release-candidate]
    - put: concourse-tests-release-candidate
      params:
        repository: concourse-tests
    - put: concourse-tests-version
      params:
        pre: rc

- name: finalize-release
  plan:
    - get: concourse-tests-version
      params:
        bump: final
    - get: concourse-tests-release-candidate
      passed: [promote-to-rc]
      params:
        fetch: [master]
    - task: tag-release
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: concourse/bosh-cli}
        inputs:
          - name: concourse-tests-version
          - name: concourse-tests-release-candidate
        run:
          path: scripts/tag-release
    - put: concourse-tests-master
      params:
        repository: concourse-tests-release-candidate
    - put: concourse-tests-version
      params:
        bump: final


