---
platform: linux

image_resource:
  type: docker-image
  source: { repository: concourse/bosh-cli }

inputs:
  - name: concourse-tests
  - name: concourse-tests-dirty

outputs:
  - name: concourse-tests-dirty

run:
  path: concourse-tests/scripts/add-timestamp-to-concourse-tests

params:
  OUTPUT_FILE: concourse-tests-dirty/data/timestamps.txt

