---
platform: linux

image_resource:
  type: docker-image
  source: { repository: concourse/bosh-cli }

inputs:
  - name: concourse-tests-dirty
    path: concourse-tests

outputs:
  - name: concourse-tests-dirty

run:
  path: concourse-tests/scripts/do-other-stuff-to-concourse-tests

params:
  OUTPUT_DIR: concourse-tests-dirty

